version: "3.8"

services:
  app:
    container_name: picklery
    build:
      context: .
    ports:
      - ${PORT}
    env_file: .env
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
