services:
  picklery:
    container_name: picklery
    build:
      context: .
    expose:
      - ${PORT}
    env_file: .env
    restart: unless-stopped
    networks:
      - pklwrks

networks:
  pklwrks:
    external: true
