RUST_VERSION := 1.79.0

.PHONY: init start

init:
	cargo build

start:
	cargo run
	
help:
	@echo "Makefile for picklery backend"
	@echo "    init     - install backend deps"
	@echo "    start    - stand up backend"
	@echo "    help     - show this help message"